import os
from fpdf import FPDF
from sqlmodel import Session, select
from app.models import Bill, BillItem, Product


class InvoiceService:
    """Generates GST-compliant PDF invoices from finalized bills."""

    SHOP_NAME = "AnandMart"
    SHOP_ADDRESS = "YourLocalKirana, Mumbai 400001"
    GSTIN = "27ABCDE1234F1Z5"

    def __init__(self, session: Session):
        self.session = session

    def generate(self, bill_id: int) -> str:
        bill = self.session.get(Bill, bill_id)
        if not bill or bill.status != "finalized":
            raise ValueError(f"Bill #{bill_id} not found or not finalized.")

        items = self.session.exec(
            select(BillItem).where(BillItem.bill_id == bill_id)
        ).all()

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=False)
        w = 190  # usable width in mm (A4 = 210mm minus 10mm margins)

        # ── Header ──
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(w, 8, self.SHOP_NAME, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(w, 5, f"GSTIN: {self.GSTIN}  |  {self.SHOP_ADDRESS}", new_x="LMARGIN", new_y="NEXT")
        pdf.line(10, pdf.get_y() + 2, 200, pdf.get_y() + 2)
        pdf.ln(5)

        # ── Bill info ──
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(w, 7, "TAX INVOICE", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        ts = bill.timestamp.strftime("%d-%b-%Y %I:%M %p") if bill.timestamp else "-"
        info_cols = [
            f"Bill #: INV-{bill.id:04d}          Date: {ts}",
            f"Payment: {bill.payment_mode or '-'}",
        ]
        for line in info_cols:
            pdf.cell(w, 5, line, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # ── Table header ──
        col_widths = [55, 18, 18, 22, 22, 22, 24]
        headers = ["Item (HSN)", "Qty", "Rate", "Taxable", "CGST", "SGST", "Total"]
        alignments = ["L", "R", "R", "R", "R", "R", "R"]

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(240, 240, 240)
        for i, (hdr, cw, al) in enumerate(zip(headers, col_widths, alignments)):
            pdf.cell(cw, 6, hdr, border=1, fill=True, align=al)
        pdf.ln()

        # ── Table rows ──
        pdf.set_font("Helvetica", "", 8)
        for item in items:
            product = self.session.get(Product, item.product_id)
            name = product.name.title() if product else "-"
            hsn = product.hsn_code or "-"
            unit = product.unit if product else ""
            rate = item.unit_price
            qty = item.quantity
            taxable = round(item.total_price - item.gst_amount, 2)
            cgst = item.cgst_amount
            sgst = item.sgst_amount

            label = f"{name} ({hsn})"
            values = [label, qty, rate, taxable, cgst, sgst, item.total_price]
            for val, cw, al in zip(values, col_widths, alignments):
                rendered = f"{val:,.0f}" if isinstance(val, (int, float)) and al != "L" else str(val)
                pdf.cell(cw, 5.5, rendered, border=1, align=al)
            pdf.ln()

        # ── Totals section ──
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 9)
        total_width = sum(col_widths)
        pdf.cell(total_width - 50, 6, "", new_x="RIGHT")
        pdf.cell(50, 6, f"Subtotal:   Rs. {round(bill.total_amount - bill.total_tax, 0):,.0f}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        pdf.cell(total_width - 50, 5, "", new_x="RIGHT")
        pdf.cell(50, 5, f"CGST:       Rs. {bill.total_cgst:,.0f}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(total_width - 50, 5, "", new_x="RIGHT")
        pdf.cell(50, 5, f"SGST:       Rs. {bill.total_sgst:,.0f}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(total_width - 50, 6, "", new_x="RIGHT")
        pdf.cell(50, 6, f"TOTAL:      Rs. {bill.total_amount:,.0f}", new_x="LMARGIN", new_y="NEXT")

        # ── Footer ──
        pdf.ln(8)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(w, 5, "This is a computer-generated invoice.", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(w, 4, "Generated by AnandMart Supermarket Agent.", new_x="LMARGIN", new_y="NEXT")

        # ── Save ──
        out_dir = "generated"
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, f"invoice_INV-{bill.id:04d}.pdf")
        pdf.output(path)
        return path
